import type { AssessmentQuestion } from "./types";

export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: "living_situation",
    title: "Current living situation",
    prompt: "Which best describes where your parent or relative is living right now?",
    helperText: "Choose the closest fit. You can refine details later.",
    options: [
      {
        id: "home_mostly_independent",
        label: "At home and mostly managing independently",
        description: "They may need planning or light support, but day-to-day life is mostly steady.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "home_with_some_help",
        label: "At home with regular help from family or services",
        description: "Support is already part of the routine, but more structure may help.",
        score: { support_at_home: 2, family_coordination: 1 },
        urgency: "medium",
      },
      {
        id: "home_support_stretched",
        label: "At home, but the current support is starting to feel stretched",
        description: "Family or informal help may no longer feel enough.",
        score: { support_at_home: 2, respite_care: 1, family_coordination: 2 },
        urgency: "medium",
      },
      {
        id: "temporary_care_or_respite",
        label: "In temporary care, respite, or staying with family",
        description: "The next stable arrangement still needs to be worked through.",
        score: { respite_care: 2, residential_care: 1, support_at_home: 1 },
        urgency: "medium",
      },
      {
        id: "hospital_or_discharge",
        label: "In hospital or recently discharged",
        description: "There may be time-sensitive decisions about safe support after discharge.",
        score: { urgent_hospital_discharge: 5, residential_care: 2, support_at_home: 1 },
        urgency: "high",
        flags: ["recent_hospital_or_decline", "hospital_discharge_now"],
      },
    ],
  },
  {
    id: "safety_at_home",
    title: "Safety at home",
    prompt: "How safe does home feel for them at the moment?",
    helperText: "This is about practical safety, not blame or judgement.",
    options: [
      {
        id: "safe_with_routine",
        label: "Generally safe with their current routine",
        description: "There are no major concerns about being at home day to day.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "some_safety_concerns",
        label: "There are some concerns, but they are manageable",
        description: "Examples might include getting tired, moving less confidently, or needing reminders.",
        score: { support_at_home: 2, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "frequent_safety_concerns",
        label: "Safety concerns are becoming frequent",
        description: "They may be at risk when alone or when family support is not available.",
        score: { residential_care: 3, support_at_home: 1, respite_care: 1 },
        urgency: "high",
        flags: ["immediate_safety_risk"],
      },
      {
        id: "not_safe_alone",
        label: "They do not seem safe to be alone right now",
        description: "This may need urgent advice from health, hospital, or aged care contacts.",
        score: { urgent_hospital_discharge: 5, residential_care: 3 },
        urgency: "high",
        flags: ["immediate_safety_risk"],
      },
    ],
  },
  {
    id: "recent_falls_or_decline",
    title: "Recent falls, hospitalisation, or sudden decline",
    prompt: "Has anything changed recently that has made care feel more urgent?",
    options: [
      {
        id: "no_recent_change",
        label: "No major recent change",
        description: "You are planning ahead or reviewing options calmly.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "minor_fall_or_change",
        label: "A fall, illness, or decline has raised concerns",
        description: "Things are manageable, but the family wants a clearer plan.",
        score: { support_at_home: 2, my_aged_care_assessment: 1 },
        urgency: "medium",
        flags: ["recent_hospital_or_decline"],
      },
      {
        id: "hospital_recently",
        label: "They have been in hospital recently",
        description: "The family is working out what support is needed next.",
        score: { urgent_hospital_discharge: 4, residential_care: 2, respite_care: 1 },
        urgency: "high",
        flags: ["recent_hospital_or_decline", "hospital_discharge_now"],
      },
      {
        id: "rapid_decline",
        label: "There has been a sudden decline and home feels hard to manage",
        description: "The situation may need urgent support and a short-term safety plan.",
        score: { urgent_hospital_discharge: 4, residential_care: 3, respite_care: 2 },
        urgency: "high",
        flags: ["immediate_safety_risk", "recent_hospital_or_decline"],
      },
    ],
  },
  {
    id: "memory_cognitive",
    title: "Memory or cognitive concerns",
    prompt: "Are memory, confusion, or decision-making concerns affecting daily life?",
    helperText: "No diagnosis is needed for this assessment.",
    options: [
      {
        id: "no_major_memory_concerns",
        label: "No major concerns at the moment",
        description: "Memory or confusion is not a key driver of care decisions right now.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "mild_memory_support",
        label: "Some reminders or gentle support are helpful",
        description: "They may need help with routines, appointments, or confidence.",
        score: { support_at_home: 2, family_coordination: 1 },
        urgency: "medium",
      },
      {
        id: "regular_confusion",
        label: "Confusion or memory changes are affecting daily safety",
        description: "Family may be needing to supervise or step in more often.",
        score: { residential_care: 3, support_at_home: 1, family_coordination: 2 },
        urgency: "medium",
        flags: ["cognitive_safety_concern"],
      },
      {
        id: "unsafe_memory_concerns",
        label: "Memory concerns make it hard for them to be safe without support",
        description: "This could include leaving appliances on, getting lost, or not recognising risks.",
        score: { residential_care: 4, urgent_hospital_discharge: 2, family_coordination: 1 },
        urgency: "high",
        flags: ["cognitive_safety_concern", "immediate_safety_risk"],
      },
    ],
  },
  {
    id: "personal_care",
    title: "Personal care needs",
    prompt: "How much help do they need with personal care such as showering, dressing, or toileting?",
    options: [
      {
        id: "personal_care_independent",
        label: "They manage personal care independently",
        description: "They may still need other kinds of support.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "personal_care_prompting",
        label: "They need prompts, reminders, or occasional help",
        description: "Support at home may be worth exploring.",
        score: { support_at_home: 2, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "personal_care_daily_help",
        label: "They need hands-on help most days",
        description: "Daily care needs may require a more formal support plan.",
        score: { support_at_home: 2, residential_care: 2, respite_care: 1 },
        urgency: "medium",
        flags: ["high_personal_care_need"],
      },
      {
        id: "personal_care_high_need",
        label: "They cannot manage most personal care safely",
        description: "A higher level of support may be needed.",
        score: { residential_care: 4, urgent_hospital_discharge: 1, respite_care: 1 },
        urgency: "high",
        flags: ["high_personal_care_need"],
      },
    ],
  },
  {
    id: "medication_health",
    title: "Medication and health management",
    prompt: "How much support do they need with medication, appointments, or health routines?",
    options: [
      {
        id: "health_independent",
        label: "They manage this independently",
        description: "Medication and appointments are not a major concern right now.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "health_reminders",
        label: "They need reminders or help keeping track",
        description: "A simple support plan could reduce family worry.",
        score: { support_at_home: 2, family_coordination: 1 },
        urgency: "medium",
      },
      {
        id: "health_family_manages",
        label: "Family or carers are managing parts of this",
        description: "The current arrangement may need clearer roles or extra services.",
        score: { support_at_home: 2, family_coordination: 2, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "health_complex_or_unstable",
        label: "Health routines feel complex or hard to manage safely",
        description: "It may be worth speaking with health professionals and exploring higher support.",
        score: { residential_care: 3, urgent_hospital_discharge: 2, family_coordination: 1 },
        urgency: "high",
        flags: ["immediate_safety_risk"],
      },
    ],
  },
  {
    id: "daily_living",
    title: "Meals, cleaning, transport, and daily living",
    prompt: "How are everyday tasks such as meals, cleaning, shopping, transport, and appointments going?",
    options: [
      {
        id: "daily_living_managing",
        label: "They are mostly managing",
        description: "Only light support or planning may be needed.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "daily_living_some_help",
        label: "They need some practical help each week",
        description: "Home support services could be relevant.",
        score: { support_at_home: 2, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "daily_living_regular_help",
        label: "They need regular help to keep daily life running",
        description: "Family may be coordinating several practical tasks.",
        score: { support_at_home: 3, family_coordination: 1 },
        urgency: "medium",
      },
      {
        id: "daily_living_struggling",
        label: "Meals, hygiene, or basic routines are becoming hard to maintain",
        description: "This may point to a higher support need.",
        score: { residential_care: 2, support_at_home: 2, respite_care: 1 },
        urgency: "high",
        flags: ["high_personal_care_need"],
      },
    ],
  },
  {
    id: "carer_capacity",
    title: "Carer stress and family capacity",
    prompt: "How is the family or main carer coping with the current level of support?",
    helperText: "It is okay to name that support is becoming hard.",
    options: [
      {
        id: "carer_capacity_ok",
        label: "The current support feels manageable",
        description: "There may still be planning to do, but the pressure is not high.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "carer_capacity_stretched",
        label: "The family is stretched but coping",
        description: "A clearer plan and shared tasks may help.",
        score: { family_coordination: 2, support_at_home: 1, respite_care: 1 },
        urgency: "medium",
        flags: ["carer_strain"],
      },
      {
        id: "carer_capacity_high_stress",
        label: "Carer stress is high",
        description: "Respite, extra services, or shared family planning may be worth considering.",
        score: { respite_care: 3, family_coordination: 3, support_at_home: 1 },
        urgency: "medium",
        flags: ["carer_strain"],
      },
      {
        id: "carer_capacity_burnout",
        label: "The main carer cannot keep going like this",
        description: "The situation may need urgent relief and a safer care plan.",
        score: { respite_care: 4, family_coordination: 3, residential_care: 2, urgent_hospital_discharge: 1 },
        urgency: "high",
        flags: ["carer_strain"],
      },
    ],
  },
  {
    id: "my_aged_care_status",
    title: "My Aged Care status",
    prompt: "Where are you up to with My Aged Care or aged care assessments?",
    options: [
      {
        id: "myac_assessed_services",
        label: "They have been assessed and have services or a package",
        description: "The next step may be reviewing whether current support still fits.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "myac_registered_waiting",
        label: "They are registered or waiting for services",
        description: "It may help to plan interim support and provider questions.",
        score: { my_aged_care_assessment: 1, support_at_home: 1 },
        urgency: "medium",
      },
      {
        id: "myac_not_contacted",
        label: "We have not contacted My Aged Care yet",
        description: "Understanding the assessment process could be an important next step.",
        score: { my_aged_care_assessment: 4, support_at_home: 1 },
        urgency: "medium",
        flags: ["my_aged_care_needed"],
      },
      {
        id: "myac_not_sure",
        label: "I am not sure where things stand",
        description: "The family may need to gather documents and confirm the current status.",
        score: { my_aged_care_assessment: 3, family_coordination: 1 },
        urgency: "medium",
        flags: ["my_aged_care_needed"],
      },
    ],
  },
  {
    id: "care_preference",
    title: "Preference for home or residential care",
    prompt: "Which direction feels closest to what your family is considering?",
    helperText: "This does not lock in a decision. It helps shape the next steps to explore.",
    options: [
      {
        id: "preference_stay_home",
        label: "They strongly prefer to stay at home",
        description: "Support at home may be the first pathway to explore.",
        score: { support_at_home: 3 },
        urgency: "low",
      },
      {
        id: "preference_home_open_respite",
        label: "They prefer home, but respite or extra support may be needed",
        description: "A mix of home support and short-term relief could be relevant.",
        score: { support_at_home: 2, respite_care: 2, family_coordination: 1 },
        urgency: "medium",
      },
      {
        id: "preference_residential_considering",
        label: "Residential care may need to be considered",
        description: "The family wants to understand fit, timing, and options.",
        score: { residential_care: 3, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "preference_residential_cost_concern",
        label: "Residential care may be needed and costs are a concern",
        description: "Cost concepts such as RAD, DAP, and ongoing fees may need careful explanation.",
        score: { residential_care: 3, financial_planning: 4 },
        urgency: "medium",
        flags: ["cost_concern"],
      },
      {
        id: "preference_unsure",
        label: "We are unsure and need a clearer pathway",
        description: "A staged plan may help the family make sense of the options.",
        score: { my_aged_care_assessment: 1, family_coordination: 1, support_at_home: 1 },
        urgency: "medium",
      },
    ],
  },
  {
    id: "timing",
    title: "Urgency and timing",
    prompt: "How soon do you need to make decisions or organise more support?",
    options: [
      {
        id: "timing_planning_ahead",
        label: "We are planning ahead",
        description: "There is time to understand options and prepare.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "timing_one_to_three_months",
        label: "Within the next 1 to 3 months",
        description: "It may be worth starting assessment and provider research soon.",
        score: { support_at_home: 1, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "timing_few_weeks",
        label: "Within the next few weeks",
        description: "The family may need a practical shortlist and near-term action plan.",
        score: { support_at_home: 2, respite_care: 2, urgent_hospital_discharge: 1 },
        urgency: "medium",
      },
      {
        id: "timing_this_week",
        label: "This week or as part of hospital discharge",
        description: "Time-sensitive support and safety planning may be needed.",
        score: { urgent_hospital_discharge: 5, residential_care: 2, respite_care: 1 },
        urgency: "high",
        flags: ["hospital_discharge_now"],
      },
    ],
  },
  {
    id: "location",
    title: "Location or suburb",
    prompt: "How clear is the location where care needs to be organised?",
    helperText: "This will later help provider search and comparison.",
    options: [
      {
        id: "location_known_suburb",
        label: "We know the suburb or local area",
        description: "Provider search can later focus on that area.",
        score: { support_at_home: 1 },
        urgency: "low",
      },
      {
        id: "location_nearby_suburbs",
        label: "We are considering a few nearby suburbs",
        description: "Comparison may need to include service coverage and travel distance.",
        score: { family_coordination: 1 },
        urgency: "low",
      },
      {
        id: "location_regional",
        label: "The care location is regional or rural",
        description: "Availability may need extra checking and earlier planning.",
        score: { support_at_home: 1, my_aged_care_assessment: 1 },
        urgency: "medium",
      },
      {
        id: "location_remote_family",
        label: "Family is coordinating from another city or state",
        description: "Shared roles and notes may help keep everyone aligned.",
        score: { family_coordination: 2 },
        urgency: "medium",
      },
      {
        id: "location_unclear",
        label: "We are not sure yet",
        description: "The family may need to decide whether care should be near home, family, or hospital.",
        score: { family_coordination: 1, my_aged_care_assessment: 1 },
        urgency: "medium",
        flags: ["location_unclear"],
      },
    ],
  },
];
