import type { Provider } from "./types";

// These are fictional demo records for MVP development. They are not real provider listings.
export const providers: Provider[] = [
  {
    id: "waratah-grove-aged-care",
    name: "Waratah Grove Aged Care",
    suburb: "Parramatta",
    state: "NSW",
    postcode: "2150",
    careTypes: ["Residential aged care", "Respite care", "Ageing in place"],
    roomTypes: ["Single room", "Private ensuite", "Companion room"],
    dementiaSupport: true,
    respiteAvailable: true,
    palliativeCare: true,
    couplesAccommodation: false,
    starRating: 4.2,
    complianceRating: 4.4,
    staffingRating: 4.1,
    residentExperienceRating: 4.0,
    qualityMeasuresRating: 4.3,
    estimatedRAD: 470000,
    estimatedDAP: 103.1,
    description:
      "A fictional metropolitan aged care home designed for demo comparisons, with a focus on family communication and supported daily routines.",
    features: ["Secure garden", "Lifestyle program", "Family meeting room", "Allied health visiting rooms"],
    contactPhone: "02 8000 1101",
    website: "https://example.com/waratah-grove",
    lastVerifiedAt: "2026-05-12",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. Families should verify all details with providers and official sources.",
    isDemoData: true,
  },
  {
    id: "bluegum-haven-care-home",
    name: "Bluegum Haven Care Home",
    suburb: "Chatswood",
    state: "NSW",
    postcode: "2067",
    careTypes: ["Residential aged care", "Dementia support", "Respite care"],
    roomTypes: ["Single room", "Private ensuite"],
    dementiaSupport: true,
    respiteAvailable: true,
    palliativeCare: false,
    couplesAccommodation: false,
    starRating: 4.6,
    complianceRating: 4.7,
    staffingRating: 4.5,
    residentExperienceRating: 4.6,
    qualityMeasuresRating: 4.4,
    estimatedRAD: 620000,
    estimatedDAP: 136.03,
    description:
      "A fictional North Shore home for MVP testing, with a calm household layout and dementia-aware support areas.",
    features: ["Memory support wing", "Quiet lounges", "Courtyard walking path", "Visiting hairdresser"],
    contactPhone: "02 8000 1102",
    website: "https://example.com/bluegum-haven",
    lastVerifiedAt: "2026-04-28",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. This is not an official provider record.",
    isDemoData: true,
  },
  {
    id: "harbourlight-residential-care",
    name: "Harbourlight Residential Care",
    suburb: "Wollongong",
    state: "NSW",
    postcode: "2500",
    careTypes: ["Residential aged care", "Palliative care", "Respite care"],
    roomTypes: ["Single room", "Private ensuite", "Couples suite"],
    dementiaSupport: false,
    respiteAvailable: true,
    palliativeCare: true,
    couplesAccommodation: true,
    starRating: 4.0,
    complianceRating: 4.2,
    staffingRating: 3.9,
    residentExperienceRating: 4.1,
    qualityMeasuresRating: 3.8,
    estimatedRAD: 430000,
    estimatedDAP: 94.33,
    description:
      "A fictional coastal care home included for demo filtering and comparison, with options for couples and short stays.",
    features: ["Coastal outlook rooms", "Couples suite option", "Respite beds", "Palliative care coordination"],
    contactPhone: "02 8000 1103",
    website: "https://example.com/harbourlight-care",
    lastVerifiedAt: "2026-05-02",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. Availability is not real-time.",
    isDemoData: true,
  },
  {
    id: "eucalypt-court-care-community",
    name: "Eucalypt Court Care Community",
    suburb: "Newcastle",
    state: "NSW",
    postcode: "2300",
    careTypes: ["Residential aged care", "Dementia support", "Ageing in place"],
    roomTypes: ["Single room", "Shared ensuite", "Private ensuite"],
    dementiaSupport: true,
    respiteAvailable: false,
    palliativeCare: true,
    couplesAccommodation: false,
    starRating: 3.8,
    complianceRating: 3.9,
    staffingRating: 3.7,
    residentExperienceRating: 3.8,
    qualityMeasuresRating: 3.7,
    estimatedRAD: 390000,
    estimatedDAP: 85.55,
    description:
      "A fictional Hunter region provider record for exploring dementia support, palliative care, and room-type comparison.",
    features: ["Dementia household", "Garden courtyard", "Music sessions", "GP visiting room"],
    contactPhone: "02 8000 1104",
    website: "https://example.com/eucalypt-court",
    lastVerifiedAt: "2026-03-19",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. Families should confirm details independently.",
    isDemoData: true,
  },
  {
    id: "riverbend-aged-care",
    name: "Riverbend Aged Care",
    suburb: "Dubbo",
    state: "NSW",
    postcode: "2830",
    careTypes: ["Residential aged care", "Respite care", "Palliative care"],
    roomTypes: ["Single room", "Shared ensuite"],
    dementiaSupport: false,
    respiteAvailable: true,
    palliativeCare: true,
    couplesAccommodation: false,
    starRating: 3.9,
    complianceRating: 4.0,
    staffingRating: 3.8,
    residentExperienceRating: 4.2,
    qualityMeasuresRating: 3.6,
    estimatedRAD: 315000,
    estimatedDAP: 69.09,
    description:
      "A fictional regional NSW home used to demonstrate location-aware comparison and indicative cost sorting.",
    features: ["Regional visiting services", "Community bus", "Respite rooms", "Outdoor barbecue area"],
    contactPhone: "02 8000 1105",
    website: "https://example.com/riverbend-aged-care",
    lastVerifiedAt: "2026-04-03",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. It is not a real provider listing.",
    isDemoData: true,
  },
  {
    id: "banksia-lodge-care-home",
    name: "Banksia Lodge Care Home",
    suburb: "Coffs Harbour",
    state: "NSW",
    postcode: "2450",
    careTypes: ["Residential aged care", "Respite care", "Ageing in place"],
    roomTypes: ["Single room", "Private ensuite", "Couples suite"],
    dementiaSupport: false,
    respiteAvailable: true,
    palliativeCare: false,
    couplesAccommodation: true,
    starRating: 4.3,
    complianceRating: 4.5,
    staffingRating: 4.0,
    residentExperienceRating: 4.4,
    qualityMeasuresRating: 4.1,
    estimatedRAD: 365000,
    estimatedDAP: 80.06,
    description:
      "A fictional mid-north coast home for demo workflows, with couples accommodation and a smaller-community feel.",
    features: ["Couples accommodation", "Vegetable garden", "Pet visiting policy", "Family dining room"],
    contactPhone: "02 8000 1106",
    website: "https://example.com/banksia-lodge",
    lastVerifiedAt: "2026-05-18",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. Families should verify information directly.",
    isDemoData: true,
  },
  {
    id: "silverband-heights-aged-care",
    name: "Silverband Heights Aged Care",
    suburb: "Penrith",
    state: "NSW",
    postcode: "2750",
    careTypes: ["Residential aged care", "Dementia support", "Palliative care"],
    roomTypes: ["Single room", "Private ensuite", "Companion room"],
    dementiaSupport: true,
    respiteAvailable: false,
    palliativeCare: true,
    couplesAccommodation: false,
    starRating: 4.1,
    complianceRating: 4.3,
    staffingRating: 3.8,
    residentExperienceRating: 4.2,
    qualityMeasuresRating: 4.0,
    estimatedRAD: 455000,
    estimatedDAP: 99.81,
    description:
      "A fictional Western Sydney care home created for MVP comparison, with dementia and palliative support indicators.",
    features: ["Secure dementia area", "Palliative support pathway", "Chapel space", "Physiotherapy room"],
    contactPhone: "02 8000 1107",
    website: "https://example.com/silverband-heights",
    lastVerifiedAt: "2026-04-22",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. It does not imply real availability.",
    isDemoData: true,
  },
  {
    id: "meadowbank-family-care-residence",
    name: "Meadowbank Family Care Residence",
    suburb: "Orange",
    state: "NSW",
    postcode: "2800",
    careTypes: ["Residential aged care", "Respite care", "Dementia support", "Ageing in place"],
    roomTypes: ["Single room", "Private ensuite", "Couples suite"],
    dementiaSupport: true,
    respiteAvailable: true,
    palliativeCare: true,
    couplesAccommodation: true,
    starRating: 4.5,
    complianceRating: 4.6,
    staffingRating: 4.3,
    residentExperienceRating: 4.7,
    qualityMeasuresRating: 4.4,
    estimatedRAD: 350000,
    estimatedDAP: 76.77,
    description:
      "A fictional Central West residence for demo use, with a broad mix of support indicators for comparison testing.",
    features: ["Couples suite option", "Dementia support", "Respite beds", "Family barbecue terrace"],
    contactPhone: "02 8000 1108",
    website: "https://example.com/meadowbank-family-care",
    lastVerifiedAt: "2026-05-20",
    dataSourceNote: "Fictional demo data created for KinHarbour MVP testing. Families should verify all information.",
    isDemoData: true,
  },
];
